version: "2"

services:
  vm:
    image: vm:1.0
    container_name: vm
    privileged: true
    working_dir: /www
    command: ["/bin/sh", "/root/start.sh"]
    volumes:
      - ./data/vm/backup:/www/backup:rw
      - ./data/vm/server:/www/server:rw
      - ./data/vm/wwwroot:/www/wwwroot:rw
      - ./data/system_log:/var/log/:rw
      - ./data/vm_log:/www/wwwlogs:rw
      - ./storage:/storage:ro
    restart: always
    ports:
      - "127.0.0.1:8022:22"
      - "127.0.0.1:8080:80"
      - "127.0.0.1:8443:443"
      - "127.0.0.1:8700:8700"
    tty: true
    cpus: 1
    mem_limit: 4G
    memswap_limit: 8G
    mem_swappiness: 40
    networks:
      - aapanel

networks:
  aapanel:
    external:
      name: cloudflared_bangunsoft
