version: "3.5"

services:
  vm:
    image: vm:1.0
    container_name: vm
    working_dir: /www
    command: ["/bin/sh", "/root/start.sh"]
    volumes:
      - ./data/vm/wwwroot:/www/wwwroot:rw
      - ./data/log/vm:/var/log/:rw
      - ./storage:/storage:ro
    restart: always
    ports:
      - "127.0.0.1:8022:22"
      - "127.0.0.1:8080:80"
      - "127.0.0.1:8443:443"
      - "127.0.0.1:8700:8700"
    tty: true

networks:
  vm-network:
    driver: bridge